apiVersion: 1

datasources:
  - name: Trino Lakehouse
    type: trino-datasource
    access: proxy
    url: http://trino:8080
    isDefault: true
    basicAuth: true
    basicAuthUser: admin
    jsonData:
      timeout: 60000
    editable: true
